### ISSUE TITLE
Show total products

### ISSUE THREAD

**Issue by viktorkalajo** [larsha/bolaget.io#1]
Hi larsha!

I would like to be able to see total number of items in /stores and /products.

Thanks!

**Comment by larsha** [comment]
@viktorkalajo Good point! 👍 Will fix this probably with a header sent back with response.

**Comment by larsha** [comment]
Fixed in this commit: https://github.com/larsha/bolaget.io/commit/74bc37b2ecdbd854ca03d38a80559531a9f44187
