### ISSUE TITLE
API:et blandar butik och produkt

### ISSUE THREAD

**Issue by elmaxe** [larsha/bolaget.io#168]
Verkar som att API:et blandar butiker och produkter om en produkt och en butik delar nr.

Kör man `https://bolaget.io/products/1611`
får man upp butik med nr `1611` istället för [Breznak](https://www.systembolaget.se/dryck/ol/breznak-161115) som har det artikelnumret.

Det fungerar även med [Oppigårds](https://www.systembolaget.se/dryck/ol/oppigards-121303) som har artikelnr 1213, då får man upp butiken med artikelnummer 1213.

Kör man `https://bolaget.io/products/1365`
får man däremot upp rätt öl. Antar det är för att den inte delar nr med en butik.

**Comment by larsha** [comment]
Tack @elmaxe, jag tittar på det!

Fix påväg ut nu, tack igen för att du hittade det!
