### ISSUE TITLE
Date for when a new product was added/found?

### ISSUE THREAD

**Issue by bjornsallarp** [larsha/bolaget.io#8]
I try to keep up with new releases but sometimes Systembolaget are very slow with updating the excel-files etc so I risk missing interesting products. If you would add the date a product was first found/added I could easily automate the task of querying for new products each day and notify myself when interesting products show up.

**Comment by larsha** [comment]
Hi @bjornsallarp, great idea, will try to find some time to fix that.

**Comment by larsha** [comment]
@bjornsallarp The `sales_start` field it not sufficient? Possible to get products like this: 
`https://bolaget.io/products?sales_start_from=2017-10-22`

Both the `sales_start_from` and `sales_start_to` can be combined.

**Comment by bjornsallarp** [comment]
I guess I could have use a sliding window and always look today and like 7 days forward. Downside is that I would have to keep a list of items I already alerted myself to avoid getting the same alert day after day. Doable for sure. Thanks!

**Comment by larsha** [comment]
@bjornsallarp Yes that's the downside. I'll see what I can do about adding a found/added parameter. I'll need to rework the whole ElasticSearch indexing because right now I'm just creating a new index and wiping the old when I have pointed the alias to the new one.
